version: '3'

services:
  db:
    build: ./database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: newsapi

  web:
    build: .
    restart: always
    ports:
      - "8598:8080"
    links:
      - "db"
    depends_on:
      - "db"
